global:
  scrape_interval: 60s

scrape_configs:
- job_name: 'prometheus'
  scrape_interval: 1m
  static_configs:
    - targets: ['localhost:9090']

- job_name: 'gateway'
  scrape_interval: 1m
  static_configs:
    - targets: ['gateway:5050']